language: python

python:
  - 3.5

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pep8

script:
  - coverage run --omit=*.virtualenvs*,*virtualenv* feast_community/manage.py test --settings=feast_community.settings members api pages
  - pep8 --count --show-source --exclude=migrations feast_community/

after_success:
  - coveralls
