# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-29 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='nom')),
                ('_type', models.CharField(choices=[('ACTIF', 'actif'), ('INACTIF', 'inactif'), ('NON_FACTURABLE', 'non-facturable')], default='ACTIF', max_length=10, verbose_name='type')),
            ],
            options={
                'verbose_name_plural': 'articles',
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='nom')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='nom')),
                ('adresse', models.CharField(max_length=100, verbose_name='adresse')),
                ('telephone', models.CharField(max_length=13, verbose_name='telephone')),
            ],
            options={
                'verbose_name_plural': 'fournisseurs',
            },
        ),
        migrations.CreateModel(
            name='LigneCatalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temps_de_livraison', models.DateTimeField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Article')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Fournisseur')),
            ],
            options={
                'verbose_name_plural': 'ligneCatalogues',
            },
        ),
        migrations.CreateModel(
            name='Prix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_minimum', models.FloatField(default=0)),
                ('quantite_minimum', models.PositiveIntegerField(default=0)),
                ('chiffre_d_affaire_minimum', models.BigIntegerField(default=0)),
                ('prix', models.FloatField(default=0)),
                ('ligneCatalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.LigneCatalogue')),
            ],
            options={
                'verbose_name_plural': 'prix',
            },
        ),
        migrations.CreateModel(
            name='Reduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pourcentage', models.PositiveSmallIntegerField()),
                ('montant_minimum', models.FloatField(default=0)),
                ('quantite_minimum', models.PositiveIntegerField(default=0)),
                ('chiffre_d_affaire_minimum', models.BigIntegerField(default=0)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Categorie')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Fournisseur')),
            ],
            options={
                'verbose_name_plural': 'reductions',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Categorie'),
        ),
    ]
