# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-29 23:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignecatalogue',
            name='temps_de_livraison',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reduction',
            name='pourcentage',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
