# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-21 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500, verbose_name='description')),
                ('code', models.CharField(max_length=10, verbose_name='code')),
                ('url', models.TextField(max_length=500, verbose_name='url')),
            ],
            options={
                'verbose_name_plural': 'error_code',
            },
        ),
    ]
